version: '3.8'

services:
  # Ollama model puller - runs once to download the model
  ollama-setup:
    image: curlimages/curl:latest
    container_name: mcprag-ollama-setup
    depends_on:
      - ollama
    volumes:
      - ./ollama-scripts:/scripts:ro
    command: sh -c "apk add --no-cache bash && /scripts/pull-models.sh"
    networks:
      - mcprag-network