version: '3.8'

services:
  # MongoDB for vector storage
  mongodb:
    image: mongo:7.0
    container_name: mcprag-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-mcprag}
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - mcprag-network

  # Ollama for LLM service
  ollama:
    image: ollama/ollama:latest
    container_name: mcprag-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./ollama-scripts:/scripts:ro
    deploy:
      resources:
        limits:
          memory: 6G
    environment:
      OLLAMA_KEEP_ALIVE: 24h
    networks:
      - mcprag-network

  # PostgreSQL for Jira
  jira-postgres:
    image: postgres:15-alpine
    container_name: mcprag-jira-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jira123
    volumes:
      - jira-postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - mcprag-network

  # Jira Software
  jira:
    image: atlassian/jira-software:9.12
    container_name: mcprag-jira
    restart: unless-stopped
    depends_on:
      - jira-postgres
    ports:
      - "8080:8080"
    environment:
      ATL_PROXY_NAME: localhost
      ATL_PROXY_PORT: 8080
      ATL_TOMCAT_SCHEME: http
      ATL_DB_TYPE: postgresql
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_JDBC_URL: jdbc:postgresql://jira-postgres:5432/jira
      ATL_JDBC_USER: jira
      ATL_JDBC_PASSWORD: jira123
      JVM_MINIMUM_MEMORY: 1536m
      JVM_MAXIMUM_MEMORY: 2048m
    volumes:
      - jira-data:/var/atlassian/application-data/jira
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - mcprag-network

  # PostgreSQL for Confluence
  confluence-postgres:
    image: postgres:15-alpine
    container_name: mcprag-confluence-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: confluence
      POSTGRES_PASSWORD: confluence123
    volumes:
      - confluence-postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - mcprag-network

  # Confluence
  confluence:
    image: atlassian/confluence:8.8
    container_name: mcprag-confluence
    restart: unless-stopped
    depends_on:
      - confluence-postgres
    ports:
      - "8090:8090"
    environment:
      ATL_PROXY_NAME: localhost
      ATL_PROXY_PORT: 8090
      ATL_TOMCAT_SCHEME: http
      ATL_DB_TYPE: postgresql
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_JDBC_URL: jdbc:postgresql://confluence-postgres:5432/confluence
      ATL_JDBC_USER: confluence
      ATL_JDBC_PASSWORD: confluence123
      JVM_MINIMUM_MEMORY: 1536m
      JVM_MAXIMUM_MEMORY: 2048m
    volumes:
      - confluence-data:/var/atlassian/application-data/confluence
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - mcprag-network

  # .NET API Service
  api:
    build:
      context: ../src
      dockerfile: McpServer.Api/Dockerfile
    image: mcprag-api:latest
    container_name: mcprag-api
    restart: unless-stopped
    depends_on:
      - mongodb
      - ollama
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__MongoDB=mongodb://admin:admin123@mongodb:27017/mcprag?authSource=admin
      - OllamaSettings__BaseUrl=http://ollama:11434
      - OllamaSettings__Model=llama3.2
      - OllamaSettings__EmbeddingModel=nomic-embed-text
      - JiraSettings__BaseUrl=http://jira:8080
      - JiraSettings__Username=admin
      - JiraSettings__ApiToken=admin123
      - ConfluenceSettings__BaseUrl=http://confluence:8090
      - ConfluenceSettings__Username=admin
      - ConfluenceSettings__ApiToken=admin123
      - IngestionSettings__LocalPath=/data/documents
      - IngestionSettings__IntervalMinutes=60
      - IngestionSettings__ChunkSize=1000
      - IngestionSettings__ChunkOverlap=200
    volumes:
      - ./data:/data:ro
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - mcprag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Blazor Client
  client:
    build:
      context: ../src
      dockerfile: McpServer.Client/Dockerfile
    image: mcprag-client:latest
    container_name: mcprag-client
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3000:80"
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - mcprag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongodb-data:
  ollama-data:
  jira-postgres-data:
  jira-data:
  confluence-postgres-data:
  confluence-data:
  api-data:
  client-data:

networks:
  mcprag-network:
    driver: bridge